### PR TITLE
Added Symbolic Links

### PR DESCRIPTION
**Pull request by J0hnBloodborne**
-Changes to nearly every function in main branch
-Lambda function to handle 2-way symlink deletion edge case (lmao)
-Now uses just <bits/stdc++.h>
-Other minor changes

### CODE REVIEW

**Comment by Nishat-Ahmad** [comment]
the pull request basically says you rewrote the whole code

**Comment by Nishat-Ahmad** [comment]
Go to view changes

**Comment by J0hnBloodborne** [comment]
just merge john

**Comment by Nishat-Ahmad** [comment]
@J0hnBloodborne the only reason i am merging it is because we have to submit it on this Thursday.

**Pull request merged**
